"""Markdown summary placeholder."""

from __future__ import annotations

from pathlib import Path


def build_summary(run_dir: str | Path) -> Path:
    run_dir = Path(run_dir)
    out = run_dir / "summary.md"
    out.write_text(
        f"""# Run Summary

- Run directory: `{run_dir.name}`
- Status: placeholder summary generated by Week 1 skeleton.

## Files

- `manifest.yaml`
- `config.yaml`
- `metrics.csv`
- `events.jsonl`

""",
        encoding="utf-8",
    )
    return out
