FROM python:3.11-slim

WORKDIR /app
COPY . /app

RUN python -m pip install --upgrade pip \
    && python -m pip install -e ".[dev,dashboard]" \
    && ruff check . \
    && pytest -q \
    && python -m build
